version: '3'
services:
  php:
    container_name: lemp_php
    build: php/
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    depends_on:
      - db

  nginx:
    container_name: lemp_nginx
    image: nginx:stable-alpine
    restart: unless-stopped

    networks:
      - webproxy
      - default

    environment:
      VIRTUAL_HOST: domain.com,www.domain.com

    volumes:
      - ./html/:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    expose:
      - "80"

  db:
    container_name: lemp_mariadb
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql/

    environment:
      - MYSQL_ROOT_PASSWORD=Deedevdb1234
      - MYSQL_DATABASE=deedev_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Deedevdb1234

networks:
  default:
    external:
      name:
        web_network
  webproxy:
    external:
      name: webproxy